apiVersion: v1
kind: Service
metadata:
  name: add-subtract-backend-service
spec:
  selector:
    app: add-subtract-backend
  ports:
    - name: server
      protocol: TCP
      port: 3001
      targetPort: 3001
    - name: websocket
      protocol: TCP
      port: 8000
      targetPort: 8000
  sessionAffinity: ClientIP
  type: LoadBalancer
